### ISSUE TITLE
Updating account information doesn't work.

### ISSUE THREAD

**Issue by jmervine** [netdna/node-netdna#11]
Test script:

```
var assert = require('assert');
var conf = {
  companyAlias:   process.env.ALIAS,
  consumerKey:    process.env.KEY,
  consumerSecret: process.env.SECRET
};

var api = require('./netdna')(conf);

api.get('account.json', function(err, res) {
  console.log('get');
  if (err) {
    console.trace(err);
  }
  console.log("name: %s", res.data.account.name)
});

api.put('account.json', '{ "name": "Node Name" }', function(err, res) {
  console.log('put -> "Node Name"');
  if (err) {
    console.trace(err);
  }
  assert.equal(res.data.account.name, "Node Name");
  console.log("name: %s", res.data.account.name)
});
```

Results:
```
get
name: New Name
put -> "Node Name"

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: "New Name" == "Node Name"
    at /home/jmervine/tmp/node-netdna/test.js:23:10
    at /home/jmervine/tmp/node-netdna/netdna.js:107:5
    at passBackControl (/home/jmervine/tmp/node-netdna/node_modules/oauth/lib/oauth.js:367:11)
    at IncomingMessage.<anonymous> (/home/jmervine/tmp/node-netdna/node_modules/oauth/lib/oauth.js:386:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

```

**Comment by jmervine** [comment]
See https://github.com/maxcdn/node-maxcdn
